"""Todo-Items Table

Revision ID: 6415a80ac638
Revises: cdc10742db64
Create Date: 2021-08-05 20:14:51.645773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6415a80ac638'
down_revision = 'cdc10742db64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo__item',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('todo_item', sa.String(length=140), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.user_id'], ),
    sa.PrimaryKeyConstraint('item_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('todo__item')
    # ### end Alembic commands ###
